    "VERIFIER",
    "N. CODE:",
    "CODE:",
    "ABS. LIM. MAX.(O/N)",
    "STANDARD (O/N)",
    "25      30      37",
    "--------------------",
    "/",
    "FACTEUR:",      /*8*/
    "STD.:",        /*9*/
    "WL1:", /*10*/
    "WL2:",
    "VOL. ECHAN.:",
    "VOL. REAC.:",
    "CALIBRATION (O/N)?",
    "STANDARD",
    "INSERER LE BLANC",    /* 16*/
    "APPUYER SUR READ",
    "COD.:",
    "BLANC STANDARD",
    "STANDARD REACTION 1",            /* 20*/
    "INSERER LE STANDARD",
    "ERREUR:2",
    "INS. ECHANT.",
    "STANDARD REACTION 2",            /* 24*/
    "ATT.:",
    "IN. BLANC ECHAN.",
    "1. 37    2. TA",
    "FILTRE:",                        /*28*/
    "ABSORPTION:",
    "ABS.:",                        /*30*/
    "ASPIRER 5 ML",
    "APPUYER LE BOUTON",
    "APPUYER ENCORE",
    "N. DE IDENT.:",
    "ETAP.",                        /*35*/
    "POUR 5 ML",
    "1. CLAVIER",
    "2. LECTURES",
    "STANDARD:",
    "LIRE.:",                     /*40*/
    "ID.:",
    "S. D.:",                     /*42*/
    "ABS.:",
    "CONC.:",
    "DE:",
    "A:",
    "IMPR. DESACTIVEE",        /*47*/
    "IMPR. ACTIVEE",
    "CODES",
    "N. DU CODE:",        /*50*/
    "LANGUAGE:",
    "ESPAGNOL",
    "ANGLAIS",
    "FRANCAIS",
    "",
    "POSITION OCCUPEE",
    "EDITER (O/N)",
    "JOUR",                /* 58 */
    "MOIS",
    "ANNEE",
    "DATE",
    "TEMPS DE REAC.:",
    "STANDARD",
    "POINT:",
    "ECHAN. REACTION 1",
    "ECHAN. REACTION 2",
    "H",
    "L",
    "SE RAPPELER",
    "FAIRE UN LAVAGE",
    "HO",                    /*71*/
    "MI",
    "SE",               /*73*/
    "FILTRE 7:",
    "FILTRE 8:",
    "Q. C.",
    "N.:",
    "DS.:",
    "CV.:",
    "R.:",
    "V. DIANA:",
    "M.:",            /*82*/
    "",
    "PAS SAUVE",
    "",
    "DESV.:",
    "",
    "1. REC. ARCHIVE",
    "2. ENV. ARCHIVE",
    "0. CLIN. ET VET.",
    "1. CLIN. ET VET. ESP.",
    "2. EAU",
    "3. ALIMENTATION",
    "",
    "",
    "100. UTILITES",
    "T. PERIS.",
    "UTILITES 2",
    "UTILITES 1",
    "1. EDIT. METHODES",
    "2. IDENT. METHODES",
    "3. IMP. METHODES",
    "4. LECT. ABS.",
    "5. ECHANGE FACTEUR",
    "6. ECHANGE STD.",
    "7. EDITION Q.C.",
    "8. VOIR Q.C.",
    "9. IMPRI. ACT/INACT.",
    "10. CAL. PERIST",
    "110. UTILITES 2",
    "11. DATE",
    "12. LANGUAGE",
    "13. APLICATIONS",
    "14. LECTURE ABSORB.",
    "15. GARDER METHODES",
    "16. FILTRES 7 Y 8",
    "17. EFFACER METHODES",
    "18. VERSION",
    "19. TEMPERATURE",
    "20. VALEUR PERIST.",
    "IDENTIFICATION:",
    "MODE:",
    "WL1:",
    "WL2:",
    "UNITES:",
    "TEMPERATURE:",
    "STD:",
    "FACTEUR:",
    "LIMIT. LIN.:",
    "N. DE LECT.:",
    "INTERVALLE:",
    "RETARD:",
    "ABS. LIM.:",
    "DT. ABS. MAX:",
    "V. N. HAUTE:",
    "V. N. BASSE:",
    "DECIMALES:",
    "V. ECHANT.:",
    "V. REACTIF:",
    "V. ASP.:",
    "T. DE RET.:",
    "T. DE REAC.:",
    "N. DE STD.:",
    " ",
    "ASPIREZ 1 ml ",
    "EAU DISTILLE ",
    " ",
    " ",
    " ",
   "ABS",  /* 150 */
   "CONC",
   "CIN",
   "FxT",
   "DIF",
   "COC",
   "MSTD",
    "",
    "CORRECT CARRY",  /* 158 */
    "MACRO",
    "SEMIMICRO",
    "MICRO",
    "DESV.:",
    "",
    "CONTROL",
    "METHODE:",
    "V. DIANA:",
    "PAS DE CONTROLE",
    "CONTROL",
    "",   /* 169 */
    "1. TEST DES FILTRES",
    "2. CALIB. TEMPER.",
    "3. TEST TEPERAT.",
    "4. VOL. AUTOLAVAGE",
    "5. CORREC CARRY",
    "6. T. RETARD",
    "7. DIF. CARRY",
    "8. FACTEUR PER.",
    "9. N. LECTURES",
    "10. TEST CANAL 1",
    "11. TEST CANAL 2", /* 180 */
    "",
    "RECEPTION FICHIER",
    "ENVOI FICHIER",
    "Q.C. CODIGO:",
    "EFF. CONTROLE (O/N)",
    "ESPACE PLEIN",
    "",
    "UTILITE 2:",
    "UTILITE 1:",
    "CLE:", /* 190 */
    "NOUV. CLE:",
    "CONFIRMEZ:",
    "CLE NON GRAVEE...",
    "CLE ERRONEE",
    "TECHN. PROTEGEES",
    "",
    "",
    "",
    "",


