   strcpy(ficher[0].code,"0");    /*absorbancia monocromatica*/
   strcpy(ficher[0].tipo,"0");
   strcpy(ficher[0].wl1,"4");
   strcpy(ficher[0].wl2,"0");
   strcpy(ficher[0].units,"1");
   strcpy(ficher[0].temp,"37");
   strcpy(ficher[0].std,"0");
   strcpy(ficher[0].factor,"2.0");
   strcpy(ficher[0].limlin,"400.0");
   strcpy(ficher[0].normalt,"105.0");
   strcpy(ficher[0].normbaj,"70.00");
   strcpy(ficher[0].sampvol,"10");
   strcpy(ficher[0].reacvol,"1000");
   strcpy(ficher[0].sipvol,"850");
   strcpy(ficher[0].readdly,"2");
   strcpy(ficher[0].reactime,"900");
   strcpy(ficher[0].absorblim,"00");
   strcpy(ficher[0].numlects,"0");
   strcpy(ficher[0].intertime,"0");
   strcpy(ficher[0].delay,"0");
   strcpy(ficher[0].dtabsmax,"0");
   strcpy(ficher[0].decs,"2");
   strcpy(ficher[0].pos_grabada,"*");


   strcpy(ficher[1].code,"1");   /*pto. final mono*/
   strcpy(ficher[1].tipo,"1");
   strcpy(ficher[1].wl1,"4");
   strcpy(ficher[1].wl2,"0");
   strcpy(ficher[1].units,"1");
   strcpy(ficher[1].temp,"30");
   strcpy(ficher[1].std,"160.0");
   strcpy(ficher[1].factor,"100.0");
   strcpy(ficher[1].limlin,"400.0");
   strcpy(ficher[1].normalt,"105.0");
   strcpy(ficher[1].normbaj,"70.00");
   strcpy(ficher[1].sampvol,"10");
   strcpy(ficher[1].reacvol,"1000");
   strcpy(ficher[1].sipvol,"850");
   strcpy(ficher[1].readdly,"2");
   strcpy(ficher[1].reactime,"900");
   strcpy(ficher[1].absorblim,"00");
   strcpy(ficher[1].numlects,"0");
   strcpy(ficher[1].intertime,"0");
   strcpy(ficher[1].delay,"0");
   strcpy(ficher[1].dtabsmax,"0");
   strcpy(ficher[1].decs,"2");
   strcpy(ficher[1].pos_grabada,"*");


   strcpy(ficher[2].code,"2");  /*cinetica mono*/
   strcpy(ficher[2].tipo,"2");
   strcpy(ficher[2].wl1,"4");
   strcpy(ficher[2].wl2,"0");
   strcpy(ficher[2].units,"1");
   strcpy(ficher[2].temp,"37");
   strcpy(ficher[2].std,"0");
   strcpy(ficher[2].factor,"1");
   strcpy(ficher[2].limlin,"0");
   strcpy(ficher[2].normalt,"2000");
   strcpy(ficher[2].normbaj,"500.0");
   strcpy(ficher[2].sampvol,"190");
   strcpy(ficher[2].reacvol,"1000");
   strcpy(ficher[2].sipvol,"1100");
   strcpy(ficher[2].readdly,"0");
   strcpy(ficher[2].reactime,"0");
   strcpy(ficher[2].absorblim,"2000");
   strcpy(ficher[2].numlects,"5");
   strcpy(ficher[2].intertime,"5");
   strcpy(ficher[2].delay,"6");
   strcpy(ficher[2].dtabsmax,"0");
   strcpy(ficher[2].decs,"2");
   strcpy(ficher[2].pos_grabada,"*");

   strcpy(ficher[3].code,"3");/*diferencial mono*/
   strcpy(ficher[3].tipo,"3");
   strcpy(ficher[3].wl1,"4");
   strcpy(ficher[3].wl2,"0");
   strcpy(ficher[3].units,"1");
   strcpy(ficher[3].temp,"37");
   strcpy(ficher[3].std,"2.0");
   strcpy(ficher[3].factor,"100");
   strcpy(ficher[3].limlin,"0");
   strcpy(ficher[3].normalt,"5000");
   strcpy(ficher[3].normbaj,"5000");
   strcpy(ficher[3].sampvol,"2");
   strcpy(ficher[3].reacvol,"2");
   strcpy(ficher[3].sipvol,"1000");
   strcpy(ficher[3].readdly,"0");
   strcpy(ficher[3].reactime,"0");
   strcpy(ficher[3].absorblim,"0");
   strcpy(ficher[3].numlects,"0");
   strcpy(ficher[3].intertime,"120");
   strcpy(ficher[3].delay,"30");
   strcpy(ficher[3].dtabsmax,"5000");
   strcpy(ficher[3].decs,"2");
   strcpy(ficher[3].pos_grabada,"*");

   strcpy(ficher[4].code,"0");    /*absorbancia bicromatica*/
   strcpy(ficher[4].tipo,"0");
   strcpy(ficher[4].wl1,"4");
   strcpy(ficher[4].wl2,"2");
   strcpy(ficher[4].units,"1");
   strcpy(ficher[4].temp,"37");
   strcpy(ficher[4].std,"0");
   strcpy(ficher[4].factor,"2.0");
   strcpy(ficher[4].limlin,"400.0");
   strcpy(ficher[4].normalt,"105.0");
   strcpy(ficher[4].normbaj,"70.00");
   strcpy(ficher[4].sampvol,"10");
   strcpy(ficher[4].reacvol,"1000");
   strcpy(ficher[4].sipvol,"850");
   strcpy(ficher[4].readdly,"2");
   strcpy(ficher[4].reactime,"900");
   strcpy(ficher[4].absorblim,"00");
   strcpy(ficher[4].numlects,"0");
   strcpy(ficher[4].intertime,"0");
   strcpy(ficher[4].delay,"0");
   strcpy(ficher[4].dtabsmax,"0");
   strcpy(ficher[4].decs,"2");
   strcpy(ficher[4].pos_grabada,"*");


   strcpy(ficher[5].code,"1");   /*pto. final bi*/
   strcpy(ficher[5].tipo,"1");
   strcpy(ficher[5].wl1,"4");
   strcpy(ficher[5].wl2,"2");
   strcpy(ficher[5].units,"1");
   strcpy(ficher[5].temp,"37");
   strcpy(ficher[5].std,"160.0");
   strcpy(ficher[5].factor,"103.0");
   strcpy(ficher[5].limlin,"400.0");
   strcpy(ficher[5].normalt,"105.0");
   strcpy(ficher[5].normbaj,"70.00");
   strcpy(ficher[5].sampvol,"10");
   strcpy(ficher[5].reacvol,"1000");
   strcpy(ficher[5].sipvol,"850");
   strcpy(ficher[5].readdly,"2");
   strcpy(ficher[5].reactime,"900");
   strcpy(ficher[5].absorblim,"00");
   strcpy(ficher[5].numlects,"0");
   strcpy(ficher[5].intertime,"0");
   strcpy(ficher[5].delay,"0");
   strcpy(ficher[5].dtabsmax,"0");
   strcpy(ficher[5].decs,"2");
   strcpy(ficher[5].pos_grabada,"*");


   strcpy(ficher[6].code,"2");  /*cinetica bi*/
   strcpy(ficher[6].tipo,"2");
   strcpy(ficher[6].wl1,"4");
   strcpy(ficher[6].wl2,"2");
   strcpy(ficher[6].units,"1");
   strcpy(ficher[6].temp,"37");
   strcpy(ficher[6].std,"0");
   strcpy(ficher[6].factor,"100");
   strcpy(ficher[6].limlin,"0");
   strcpy(ficher[6].normalt,"2000");
   strcpy(ficher[6].normbaj,"500.0");
   strcpy(ficher[6].sampvol,"190");
   strcpy(ficher[6].reacvol,"1000");
   strcpy(ficher[6].sipvol,"1100");
   strcpy(ficher[6].readdly,"0");
   strcpy(ficher[6].reactime,"0");
   strcpy(ficher[6].absorblim,"2000");
   strcpy(ficher[6].numlects,"4");
   strcpy(ficher[6].intertime,"15");
   strcpy(ficher[6].delay,"20");
   strcpy(ficher[6].dtabsmax,"0");
   strcpy(ficher[6].decs,"2");
   strcpy(ficher[6].pos_grabada,"*");

   strcpy(ficher[7].code,"3");/*diferencial bi*/
   strcpy(ficher[7].tipo,"3");
   strcpy(ficher[7].wl1,"4");
   strcpy(ficher[7].wl2,"2");
   strcpy(ficher[7].units,"1");
   strcpy(ficher[7].temp,"37");
   strcpy(ficher[7].std,"50.0");
   strcpy(ficher[7].factor,"0");
   strcpy(ficher[7].limlin,"0");
   strcpy(ficher[7].normalt,"5000");
   strcpy(ficher[7].normbaj,"5000");
   strcpy(ficher[7].sampvol,"2");
   strcpy(ficher[7].reacvol,"2");
   strcpy(ficher[7].sipvol,"1000");
   strcpy(ficher[7].readdly,"0");
   strcpy(ficher[7].reactime,"0");
   strcpy(ficher[7].absorblim,"0");
   strcpy(ficher[7].numlects,"0");
   strcpy(ficher[7].intertime,"15");
   strcpy(ficher[7].delay,"15");
   strcpy(ficher[7].dtabsmax,"5000");
   strcpy(ficher[7].decs,"2");
   strcpy(ficher[7].pos_grabada,"*");

