   extern double flo1;
   extern double flo2;

   extern int inf;
   extern int veri[];
   extern int debr;

   extern unsigned char a1;
   extern char nuinf[];
   extern unsigned char a2;

    extern int orden[4][17];


    extern int orden1[];

   extern long int tiempo;
   extern unsigned int tempo;
   extern unsigned int tempo1;
   extern unsigned int segundo;
   extern unsigned char time;

   extern long int ceroe;
   extern unsigned int start,ihi,segs1;

   extern unsigned char b;
   extern double flo;

   extern long int d;

   extern unsigned char e;

   extern int f;

   extern  unsigned char g1;

   extern unsigned int h1;

   extern unsigned char i1;
   extern long int factor;

   extern int gyu;


   extern double v1,v2,v3,v4;

   extern int nconv;
   extern int fconv;
   extern unsigned char ad[130];
   extern int ghj;
   extern int pp1;


   extern int ty;
   extern int nty[7];
   extern unsigned int nth;
   extern double rt;

   extern int veces;


   extern unsigned char recip[50],*rec;
   extern unsigned char dat,*menp;

   extern int temp1; /*contador para la base de tiempos*/
   extern int temp2; /*contador para la base de tiempos*/
   extern int segs;




   extern unsigned  char tco,t,h;

  extern char tecla;

  extern char disp[10];

  extern int cont[24],cong,conx,ncont;

  extern int valor,mayor;
  extern float total;
  extern int ki;
  extern char resto;

/* TEXTOS DEL PROGRAMA                             */

    extern char * const textos[];
/*-------------------------------------------------*/


/*  TEXTOS Y DATOS PARA LA PROGRAMACION DE TECNICAS */

  extern struct tecnicas {
   char code[2];
   char tipo[2];
   char wl1[2];
   char wl2[2];
   char units[2];
   char temp[3];
   char std[7];
   char factor[7];
   char limlin[7];
   char normalt[8];
   char normbaj[8];
   char sampvol[6];
   char reacvol[6];
   char sipvol[6];
   char readdly[6];
   char reactime[6];
   char absorblim[16];
   char numlects[3];
   char intertime[4];
   char delay[4];
   char dtabsmax[6];
   };

   extern char *tecn[];

   extern struct tecnicas ficher[10];

   extern struct tecnicas *puntfic;
   extern char *offsfic;

  extern offstecn[];


   extern unsigned char *lin[10][20];

   extern unsigned char *units[];
   extern unsigned char *wl[];
   extern unsigned char *tipos[];
   extern unsigned char *codigos[];
   extern unsigned char *txt_prog[];

/* -------------------------------------------------*/


  extern unsigned char ent[20];
  extern char spac[50];

   extern unsigned char lado;
   extern unsigned char de[15],iz[15],paso;

