    "CHECK",
    "N. DE CODIGO:",
    "CODIGO:",
    "ABS. LIM. MAX.(S/N)",
    "STANDARD (S/N)",
    "25      30      37",
    "----------------------",
    "/",
    "FACTOR:",      /*8*/
    "STD.:",        /*9*/
    "WL1:",         /*10*/
    "WL2:",
    "VOL. MUESTRA:",
    "VOL. REACTIVO:",
    "CALIBRAR (S/N)?",
    "STANDARD",
    "PONGA BLANCO",    /* 16*/
    "PULSE READ",
    "COD.:",
    "BLANCO DE STANDARD",
    "STANDARD REACCION 1",            /* 20*/
    "PONGA STANDARD",
    "ERROR:2",
    "PONGA MUESTRA",
    "STANDARD REACCION 2",            /* 24*/
    "ESP.:",
    "BLANCO MUESTRA",
    "1. 37    2. TA",
    "FILTRO:",                        /*28*/
    "ABSORCION:",
    "ABS.:",                        /*30*/
    "ASPIRE 5 ML",
    "ACCIONE PULSADOR ",
    "VUELVA A ACCIONAR ",
    "N. PACIENTE:",
    "TIEMPO",                        /*35*/
    "PARA 5 ML",
    "1. POR TECLADO",
    "2. POR LECTURA",
    "STANDARD:" ,
    "LECT.:" ,                     /*40*/
    "ID.:",
    "D. S.:",                     /*42*/
    "ABS.:",
    "CONC.:",
    "DESDE:",
    "HASTA:",
    "IMPRESORA DESACT.",        /*47*/
    "IMPRESORA ACT.",
    "CODIGOS POSIBLES",
    "NUMERO DE COD.:",        /*50*/
    "IDIOMA",
    "CASTELLANO:",
    "INGLES:",
    "FRANCES",
    "",
    "POSICION OCUPADA",
    "EDITAR (S/N)",
    "DD",                    /*58*/
    "MM",
    "AA",               /*60*/
    "FECHA",
    "T. REACCION:",
    "STANDARD",
    "PUNTO:",
    "MUESTRA REACCION 1",
    "MUESTRA REACCION 2",
    "A",
    "B",
    "RECUERDE QUE DEBE",
    "HACER UN LAVADO",      /*70*/
    "HO",                    /*71*/
    "MI",
    "SE",               /*73*/
    "FILTRO 7:",
    "FILTRO 8:",
    "Q. C.",
    "N.:",
    "DS.:",
    "CV.:",
    "R.:",
    "V. DIANA:",
    "M.:",            /*82*/
    "",
    "NO GRABADA",
    "",
    "DESV.:",
    "",
    "1. REC. FICHERO",
    "2. ENV. FICHERO",
    "0. CLIN. Y VET.",
    "1. CLIN. Y VET. ESP.",
    "2. AGUAS",
    "3. ALIMENTACION",
    "",
    "",
    "100. UTILIDADES",
    "T. PERIS.",
    "UTILIDADES 2",
    "UTILIDADES 1",
    "1. EDICION TECNICAS",
    "2. IDENT. TECNICAS",
    "3. IMP. TECNICAS",
    "4. LECT. ABS.",
    "5. CAMB. FACTOR",
    "6. CAMB. STD.",
    "7. EDITAR Q.C.",
    "8. Q.C.",
    "9. ACT/DESACT IMP.",
    "10. CAL. PERIST",
    "110. UTILIDADES 2",
    "11. FECHA",
    "12. IDIOMA",
    "13. APLICACIONES",
    "14. IMPR. ABSORB.",
    "15. CARGA DE TECN.",
    "16. FILTROS 7 Y 8",
    "17. BORRAR TECNICAS",
    "18. VERSION",
    "19. TEMPERATURA",
    "20. VALOR PERIST",
    "IDENTIFICACION:",
    "MODO:",
    "WL1:",
    "WL2:",
    "UNIDADES:",
    "TEMPERATURA:",
    "STD:",
    "FACTOR:",
    "LIMIT. LIN.:",
    "N. DE LECTS.:",
    "INTERVALO:",                             
    "ESPERA:",
    "ABS. LIM.:",
    "DT. ABS. MAX:",
    "NORM. ALTO:",
    "NORM. BAJO:",
    "DECIMALES:",
    "V. MUESTRA:",
    "V. REACTIVO:",
    "V. ASPIR.:",
    "RETARDO LECT.:",                                
    "TIEMPO REAC.:",
    "N. STANDARDS:",
    " ",
    "ASPIRAR 1 ml DE",
    "AGUA DESTILADA ",
    " ",
    " ",
    " ",
   "ABS",  /* 150 */
   "CONC",
   "CIN",
   "FxT",
   "DIF",
   "COC",
   "MSTD",
    "",
    "CORREGIR CARRY",  /* 158 */
    "MACRO",
    "SEMIMICRO",
    "MICRO",
    "DESV.:",
    "",
    "CONTROL",
    "TECNICA:",
    "V. DIANA:",
    "CONTROL NO EXISTE",
    "CONTROL",
    "",   /* 169 */
    "1. TEST FILTROS",
    "2. CAL. TEMPER.",
    "3. TEST TEPERAT.",
    "4. VOL. AUTOLAV.",
    "5. CORREC CARRY",
    "6. T. ESPERA",
    "7. DIF. CARRY",
    "8. FACTOR PER.",
    "9. N. LECTURAS",
    "10. TEST CANAL 1",
    "11. TEST CANAL 2", /* 180 */
    "",
    "RECIBIENDO FICHERO",
    "ENVIANDO FICHERO",
    "Q.C. CODIGO:",
    "BORRAR CONTROL (S/N)",
    "ESPACIO LLENO",
    "",
    "UTILIDAD 2:",
    "UTILIDAD 1:",  
    "CLAVE:", /* 190 */
    "CLAVE NUEVA:",
    "CONFIRMAR:",
    "CLAVE NO GRABADA...",
    "CLAVE ERRONEA",
    "TECNICAS A PROTEGER",
    "",
    "",
    "",
    "",
     
 
